### ISSUE TITLE
Serial-only use?

### ISSUE THREAD

**Issue by jcw** [nealcrook/multicomp6809#14]
Hello - I'm trying to bring up your 6809 config on a bare EP2C5 with just a serial FTDI adapter connected.
The reason is that the RAM chip isn't working yet (I suspect a faulty A7 addr on pin 143, easily adjusted later).
To help with troubleshooting, I've rebuilt a minimal system - the goal is to  first get 6809 + CamelForth going.
From there, it will hopefully be easier to work through the remaining issues one by one.

Looking through the `chromium.lst` blocks, I see `SCCINIT` calls, so presumably both UARTs are being inited.
But I can't figure out whether they also act as alt console, if there is no PS/2+VGA hardware present (yet)?

**Comment by nealcrook** [comment]
Hi, the console I/O in CamelForth always uses the port, at FFD0.

By default, this is the PS/2+VGA interface. However, if you tie input VDUFFD0 low it swaps the port decode, so that the serial port is decoded at FFD0 (and the PS/2+VGA is then decoded at FFD2). The .qsf files shows that VDUFFD0 is pin 48 and that it has an internal pull-up on it. You can safely wire it directly to GND.

regards,
Neal.

**Comment by nealcrook** [comment]
BTW, I have some bare PCB and would be happy to send you one if you cover the postage cost from the UK.

**Comment by jcw** [comment]
Ah - thx, that will fix it! (I misread, and assumed VDUFF0 only swapped _between_ the two serial ports ...)

Yes, a PCB would be great. Could you invoice me via PayPal? (please do also charge for the PCB)
I think PayPal will give you my address once paid. See email address in my github profile.

**Comment by jcw** [comment]
```
6809 CamelForth v1.1  20 Mar 16
1 2 + . 3
OK
```

Bingo!
